### ISSUE TITLE
`fallback` missing properties using npm to install

### ISSUE THREAD

**Issue by stellarpower** [jldec/marked-forms#2]
Hey there,

I installed this package a couple of days ago and have encountered an issue using it, I had hoped that by now I'd have submitted a PR but I'm afraid I'm just going round in circles and my head is completely frazzled by now and I can't spend any longer on it. I had a fix working and now seem to be back to square one.

The problem is that the fallback object is missing the functions from renderer; hence, when I pass in any markdown containing any ordinary markup, node makes some sort of compalaint about a missing property or undefined - e.g. `link`, `paragraph`, etc.

Below is the (minimal) build script I have been using, and the accompanying file containing some sample markdown.

`build.js:`
```javascript
var marked = require('marked');
var renderer = new marked.Renderer();
var fs = require('fs');
 
/*renderer = */ require('marked-forms')(renderer, marked);
 
var html = marked(fs.readFileSync('form.md', 'utf8'), {renderer:renderer});
fs.writeFileSync('form.html', html, 'utf8');
```

`form.md:`
```markdown
[Provide a Name ??]()
[Choose one ?select?](nme)
- option 1 "val1"
- option 2 "val2"
- option 3 "hello"

[Hello](google.com)
1. hi
1. bonjour
1. goddag

```

 By this afternoon I thought I had corrected the error, however what has complicated the issue is that
1. The behaviour seems to be totally different when I install the package by cloning from github, or using `npm i`, even though *both versions are at 2.1.0*
1. There seems to be a potential bug with the checkboxes where I get garbled output unless I leave a blank line at the end after the last option, which means I may have discarded some of my earlier tests/code. (a)

I'll gladly help fix this if I can but I'm afraid I just need to get on with what I was using this for at the moment and I really don't like javascript for issues like this I've had in the past so I decided at this point it was best to cut losses and submit a bug instead as you know what you're doing better than I.

# Details

## 1. If I clone the repository
- Running `npm test` passes all 65 tests
- Running `node build.js` outputs the correct html, both with exclusively forms markdown, and a combination of forms and 'normal' markdown, except for (potential?) bug (a)

## 2. If I use `npm i marked-forms`
- Some googling has not revealed how to (download and) run tests for dependency packages so I'm afraid I don't know how to unit test the package as installed under npm; in the node_modules folder, I can't see any of the testsuite. (I'm kinda used to ruby gems where the unit tests are disributed with the library and run on import so the process is the same as normal installation :^) )
- Using build.js outputs an error at e.g. line 72, 51, wherever a Marked.Renderer function is called onthe fallback object.

## 3. Reassignment
- In `test-marked-renderer.js`, the output of `require`ing is assigned back to the renderer, in the readme, this is absent.
- I thought that this was the cause of the issue, however now it seems that given that the differencei n behaviour depends on whether or not I use the github clone or the np package, this was masking it and cleaning out my own code and starting afresh, I think this actually makes no difference - in the code as it is, `fallback` is a clone of `renderer`, and renderer is mutated by the function but not reassigned anywhere, so it makes no difference whether you keep or discard the returned reference to the renderer because it's referring to the same object as the reference in higher scope in 'build.json', and so we return it as a courtesy/expected behaviour in JS/what have you.

## 4. Invisible Properties
- In case (2) the errors are caused by missing properties - I have used a variety of methods (enumerating using `for`, `Object.hasOwnProperty`, `Object.getOwnPropertyNames`, `Object.getOwnPropertySymbols`, ...) and it seems the renderer's functions are completely hidden from view, unless you have the name of the specific function, and as such, not included in any clone, using either the `clone` function provided or other methods in JS. When using the git version, however, fallback seems to be fully populated with the renderer functions. Therefore, when using the git version, `build.js` just seems to work, but using npm, it will fail whenever any non-form markdown is in the file.
- I had worked around this using:
```
function patch(renderer, property, newValue){
  fallback[property] = renderer[property];
  renderer[property] = newValue;
}

...

  fallback = {};

  // mutate renderer with forms-capable methods
  patch(renderer, 'link', link);
  patch(renderer, 'listitem', listitem);
  patch(renderer, 'list', list);
  patch(renderer, 'paragraph', paragraph);

```

Thus, for whatever reason that fallback doesn't clone properly, if we treat it as more of a hash keeping a reference to the original functions, then the code still works.

Please let me know if there's any more information I can provide, or equally, if I'm just doing something nonsensical on my end and this isn't a bug.

Cheers

**Comment by jldec** [comment]
Hi @stellarpower,

I found the same issue as you did today when i upgraded dependencies to marked v0.8.0. The package.json was missing a peerdependency version for `marked`, so when you cloned and installed, it was using marked v0.7.0 to run the test, but when you pulled in marked on your own project you probably got the more recent version.

I have fixed the issue and published a new release on npm.  
I also added a peerdependency so that this doesn't happen again.  
And I'll try to be better in future watching this repo for issues, and updating dependencies.

Thanks for the detailed report and patch.
